In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# 1.Data Read

In [5]:
df = pd.read_csv("sample.csv")

In [23]:
df.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
0,56.22,67.39,45.24,31.11,44.21,50.49,41.96,68.99,58.52,71.48,...,63.42,83.27,61.54,75.28,75.30,78.14,124.73,43.81,122.37,59.89
1,49.55,62.17,51.34,43.68,54.61,50.11,48.48,33.11,51.70,76.10,...,65.41,67.73,71.46,53.76,60.79,76.81,71.58,70.27,81.55,58.94
2,57.80,52.66,43.89,49.04,55.23,32.66,44.28,68.01,56.50,67.48,...,67.16,50.12,93.84,82.48,63.24,51.80,65.44,97.81,68.86,107.07
3,66.99,44.88,49.46,76.65,60.91,51.71,49.60,54.73,69.36,30.86,...,83.04,58.44,67.15,57.49,58.48,82.88,61.03,74.48,95.49,116.95
4,48.54,59.68,31.22,60.68,37.91,65.53,54.11,67.90,77.53,57.67,...,52.55,73.34,51.16,83.62,108.35,40.45,79.90,93.19,92.53,54.10

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   feature_1   1000 non-null   float64
 1   feature_2   1000 non-null   float64
 2   feature_3   1000 non-null   float64
 3   feature_4   1000 non-null   float64
 4   feature_5   1000 non-null   float64
 5   feature_6   1000 non-null   float64
 6   feature_7   1000 non-null   float64
 7   feature_8   1000 non-null   float64
 8   feature_9   1000 non-null   float64
 9   feature_10  1000 non-null   float64
 10  feature_11  1000 non-null   float64
 11  feature_12  1000 non-null   float64
 12  feature_13  1000 non-null   float64
 13  feature_14  1000 non-null   float64
 14  feature_15  1000 non-null   float64
 15  feature_16  1000 non-null   float64
 16  feature_17  1000 non-null   float64
 17  feature_18  1000 non-null   float64
 18  feature_19  1000 non-null   float64
 19  feature_20  1000 non-null   float64
 20  feature_21  1000 non-null   float64
 21  feature_22  1000 non-null   float64
 22  feature_23  1000 non-null   float64
 23  feature_24  1000 non-null   float64
 24  feature_25  1000 non-null   float64
dtypes: float64(25)
memory usage: 195.4 KB

In [27]:
df.describe()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,51.203000,52.779250,53.066930,53.775430,54.38402,55.392200,56.619800,58.269120,59.265900,59.819580,...,65.87005,67.549590,68.610210,68.924010,70.637550,70.195430,72.864510,71.720420,73.747190,74.489700
std,10.281713,10.971937,11.309887,12.325592,12.40465,13.096107,13.837517,14.584319,14.669392,14.476842,...,18.41236,18.364995,19.091175,19.346262,20.101064,20.764184,20.609149,21.655655,21.244072,21.312291
min,16.970000,19.660000,18.280000,18.850000,15.29000,18.310000,20.380000,6.360000,3.370000,1.160000,...,0.57000,12.730000,11.090000,3.950000,-7.130000,5.420000,4.530000,-5.580000,12.680000,-3.640000
25%,44.200000,45.332500,45.545000,45.152500,46.46500,46.982500,46.805000,48.307500,49.770000,50.347500,...,53.87250,54.535000,55.767500,55.887500,57.060000,56.047500,58.715000,56.942500,58.212500,60.207500
50%,51.265000,52.695000,52.995000,54.005000,54.77000,55.440000,56.260000,58.070000,59.275000,60.065000,...,65.88000,67.600000,68.960000,68.245000,71.020000,69.810000,72.535000,71.390000,73.850000,75.285000
75%,57.802500,60.015000,60.600000,62.007500,62.99250,63.962500,66.442500,68.125000,68.820000,69.760000,...,78.32250,80.157500,81.512500,82.642500,84.067500,84.565000,86.797500,86.580000,88.442500,88.792500
max,91.450000,87.120000,98.150000,92.920000,93.91000,96.280000,104.640000,101.650000,107.970000,101.530000,...,146.62000,122.130000,126.840000,145.880000,128.610000,144.860000,147.840000,136.070000,143.010000,143.360000

In [29]:
df.shape

(1000, 25)

In [31]:
df.columns

Index(['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5',
       'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10',
       'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15',
       'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20',
       'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25'],
      dtype='object')

## Data Processing

### 1. Data is null

In [35]:
df.isna().sum()

feature_1     0
feature_2     0
feature_3     0
feature_4     0
feature_5     0
feature_6     0
feature_7     0
feature_8     0
feature_9     0
feature_10    0
feature_11    0
feature_12    0
feature_13    0
feature_14    0
feature_15    0
feature_16    0
feature_17    0
feature_18    0
feature_19    0
feature_20    0
feature_21    0
feature_22    0
feature_23    0
feature_24    0
feature_25    0
dtype: int64

In [37]:
df.dropna()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
0,56.22,67.39,45.24,31.11,44.21,50.49,41.96,68.99,58.52,71.48,...,63.42,83.27,61.54,75.28,75.30,78.14,124.73,43.81,122.37,59.89
1,49.55,62.17,51.34,43.68,54.61,50.11,48.48,33.11,51.70,76.10,...,65.41,67.73,71.46,53.76,60.79,76.81,71.58,70.27,81.55,58.94
2,57.80,52.66,43.89,49.04,55.23,32.66,44.28,68.01,56.50,67.48,...,67.16,50.12,93.84,82.48,63.24,51.80,65.44,97.81,68.86,107.07
3,66.99,44.88,49.46,76.65,60.91,51.71,49.60,54.73,69.36,30.86,...,83.04,58.44,67.15,57.49,58.48,82.88,61.03,74.48,95.49,116.95
4,48.54,59.68,31.22,60.68,37.91,65.53,54.11,67.90,77.53,57.67,...,52.55,73.34,51.16,83.62,108.35,40.45,79.90,93.19,92.53,54.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48.05,63.77,53.89,54.34,54.39,58.23,52.98,88.94,60.47,79.52,...,74.47,69.57,86.71,68.07,77.76,61.96,95.11,45.93,99.62,61.37
996,69.88,51.71,55.96,29.07,63.89,70.98,67.38,62.58,75.92,30.02,...,87.43,86.49,53.12,74.27,97.55,100.94,33.71,80.65,88.71,68.53
997,57.73,42.30,38.72,50.16,93.91,40.17,49.88,46.31,82.03,49.42,...,60.91,106.41,82.92,69.43,77.57,94.82,45.74,90.86,78.62,96.78
998,45.00,50.21,56.84,73.72,65.10,62.08,56.93,81.14,49.07,67.44,...,77.78,80.90,46.16,74.48,104.27,75.27,68.30,70.95,78.52,89.03
999,57.01,43.81,51.21,58.33,44.40,40.79,62.38,87.09,70.62,69.67,...,76.17,72.46,87.60,67.23,37.60,25.15,79.43,99.62,85.84,75.35

In [39]:
df.fillna(0)

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
0,56.22,67.39,45.24,31.11,44.21,50.49,41.96,68.99,58.52,71.48,...,63.42,83.27,61.54,75.28,75.30,78.14,124.73,43.81,122.37,59.89
1,49.55,62.17,51.34,43.68,54.61,50.11,48.48,33.11,51.70,76.10,...,65.41,67.73,71.46,53.76,60.79,76.81,71.58,70.27,81.55,58.94
2,57.80,52.66,43.89,49.04,55.23,32.66,44.28,68.01,56.50,67.48,...,67.16,50.12,93.84,82.48,63.24,51.80,65.44,97.81,68.86,107.07
3,66.99,44.88,49.46,76.65,60.91,51.71,49.60,54.73,69.36,30.86,...,83.04,58.44,67.15,57.49,58.48,82.88,61.03,74.48,95.49,116.95
4,48.54,59.68,31.22,60.68,37.91,65.53,54.11,67.90,77.53,57.67,...,52.55,73.34,51.16,83.62,108.35,40.45,79.90,93.19,92.53,54.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48.05,63.77,53.89,54.34,54.39,58.23,52.98,88.94,60.47,79.52,...,74.47,69.57,86.71,68.07,77.76,61.96,95.11,45.93,99.62,61.37
996,69.88,51.71,55.96,29.07,63.89,70.98,67.38,62.58,75.92,30.02,...,87.43,86.49,53.12,74.27,97.55,100.94,33.71,80.65,88.71,68.53
997,57.73,42.30,38.72,50.16,93.91,40.17,49.88,46.31,82.03,49.42,...,60.91,106.41,82.92,69.43,77.57,94.82,45.74,90.86,78.62,96.78
998,45.00,50.21,56.84,73.72,65.10,62.08,56.93,81.14,49.07,67.44,...,77.78,80.90,46.16,74.48,104.27,75.27,68.30,70.95,78.52,89.03
999,57.01,43.81,51.21,58.33,44.40,40.79,62.38,87.09,70.62,69.67,...,76.17,72.46,87.60,67.23,37.60,25.15,79.43,99.62,85.84,75.35

### 2. Data Duplicate

In [46]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [48]:
df.drop_duplicates()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
0,56.22,67.39,45.24,31.11,44.21,50.49,41.96,68.99,58.52,71.48,...,63.42,83.27,61.54,75.28,75.30,78.14,124.73,43.81,122.37,59.89
1,49.55,62.17,51.34,43.68,54.61,50.11,48.48,33.11,51.70,76.10,...,65.41,67.73,71.46,53.76,60.79,76.81,71.58,70.27,81.55,58.94
2,57.80,52.66,43.89,49.04,55.23,32.66,44.28,68.01,56.50,67.48,...,67.16,50.12,93.84,82.48,63.24,51.80,65.44,97.81,68.86,107.07
3,66.99,44.88,49.46,76.65,60.91,51.71,49.60,54.73,69.36,30.86,...,83.04,58.44,67.15,57.49,58.48,82.88,61.03,74.48,95.49,116.95
4,48.54,59.68,31.22,60.68,37.91,65.53,54.11,67.90,77.53,57.67,...,52.55,73.34,51.16,83.62,108.35,40.45,79.90,93.19,92.53,54.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48.05,63.77,53.89,54.34,54.39,58.23,52.98,88.94,60.47,79.52,...,74.47,69.57,86.71,68.07,77.76,61.96,95.11,45.93,99.62,61.37
996,69.88,51.71,55.96,29.07,63.89,70.98,67.38,62.58,75.92,30.02,...,87.43,86.49,53.12,74.27,97.55,100.94,33.71,80.65,88.71,68.53
997,57.73,42.30,38.72,50.16,93.91,40.17,49.88,46.31,82.03,49.42,...,60.91,106.41,82.92,69.43,77.57,94.82,45.74,90.86,78.62,96.78
998,45.00,50.21,56.84,73.72,65.10,62.08,56.93,81.14,49.07,67.44,...,77.78,80.90,46.16,74.48,104.27,75.27,68.30,70.95,78.52,89.03
999,57.01,43.81,51.21,58.33,44.40,40.79,62.38,87.09,70.62,69.67,...,76.17,72.46,87.60,67.23,37.60,25.15,79.43,99.62,85.84,75.35

### 3. Data Type Transfer

In [58]:
#df["date"] = pd.date_range(start="2024-01-01", periods=len(df), freq="D")

df["date"] = pd.to_datetime(df["date"])

#df["feature"] = df["feature"].astype(float)

### 4. Data Condition Selection

In [67]:
# df1=df[df["feature_1"] > 50]
df1=df[(df["feature_1"] > 50) & (df["feature_2"] < 40)]
df1.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,date
31,70.45,33.65,41.80,46.10,37.30,72.31,51.26,50.55,80.78,56.41,...,45.19,75.50,35.04,121.23,95.31,53.54,107.39,66.35,63.17,2024-02-01
36,53.19,38.52,57.51,49.89,61.46,84.41,68.64,36.00,36.48,60.50,...,75.78,72.61,44.98,91.22,89.31,101.19,77.72,104.88,48.37,2024-02-06
47,62.10,34.66,52.89,49.96,90.18,55.71,77.69,56.70,48.75,59.09,...,42.64,56.54,50.99,89.92,54.23,65.52,94.23,50.09,85.96,2024-02-17
65,65.24,39.68,46.30,57.86,47.09,53.34,53.32,44.85,60.31,54.49,...,71.63,86.74,84.28,72.95,35.10,100.78,94.79,79.43,60.37,2024-03-06
66,50.24,37.76,24.95,75.06,57.37,56.41,45.72,52.62,75.88,46.55,...,84.09,70.29,84.46,51.29,83.99,109.58,65.60,78.67,112.46,2024-03-07

## Data Condition

### 5. Group By

In [77]:
#df_1 = df.groupby("feature_2")["feature_1"].mean()
#按照 feature_4 的数值把数据分堆，然后对每一堆里的其他列进行不同的数学计算
df_1 = df.groupby("feature_4").agg({"feature_1": "mean","feature_2": "sum","feature_3": "count"})
df_1

           feature_1  feature_2  feature_3
feature_4
18.85          45.43      58.22          1
19.12          43.86      44.97          1
20.01          54.30      46.68          1
22.76          40.97      47.90          1
23.61          57.54      43.68          1
...              ...        ...        ...
83.82          48.48      46.89          1
84.14          53.67      42.90          1
88.42          49.80      49.76          1
91.82          40.85      45.11          1
92.92          52.20      55.65          1

[886 rows x 3 columns]

### 6.Pivot Table

In [21]:
#df.pivot_table(index='feature_1', values=['feature_2', 'feature_3'], aggfunc='mean').head()
df.pivot_table(index='feature_1', values=['feature_2', 'feature_3'], aggfunc='sum').head()
#df.pivot_table(index='feature_1', values=['feature_2', 'feature_3'], aggfunc='count').head()

           feature_2  feature_3
feature_1
16.97          57.93      67.21
22.68          49.94      48.74
23.16          61.25      59.35
23.49          62.96      45.90
25.05          45.38      80.91

In [98]:
#查看出现pair对的总共有多少次
result= df.groupby(["feature_1", "feature_2"]).size().reset_index(name="number")

repeat_data = result[result['number'] > 1]

## SQL

### 1. Create Table

In [ ]:
CREATE TABLE students (
    id INT PRIMARY KEY,        -- 唯一标识
    name VARCHAR(50),          -- 字符串，最大长度50
    age INT,                   -- 整数
    score DECIMAL(5, 2)        -- 小数，如 98.50
);

In [ ]:
SELECT * FROM students
SELECT name, score, AVG(score) FROM students
SELECT DISTINCT gender FROM students

SELECT * FROM students WHERE score > 80 AND age < 25
SELECT * FROM students WHERE name LIKE '张%'
SELECT * FROM students ORDER BY score DESC

INNER JOIN classes ON students.class_id = classes.id;

GROUP BY gender
ORDER BY score DESC 
HAVING AVG(score) > 80; -- 这里的过滤是针对“平均分”这个聚合结果的

LIMIT 5
LIMIT 10 OFFSET 10（跳过前 10 条，从第 11 条开始取 10 条）


WHERE age != 18
WHERE id IN (1, 3, 5)
WHERE score BETWEEN 60 AND 100
WHERE email IS NULL

In [ ]:
SELECT gender, COUNT(*) 
FROM students 
GROUP BY gender; -- 按性别分组统计人数

SELECT gender, course, COUNT(*) AS cnt
FROM students
GROUP BY gender, course;