In [4]:
# yfinance all stock
import yfinance as yf

tickers = ["AAPL", "AMZN", "GOOG", "INTC", "MSFT"]

# 可选 interval: “1m", "2m", "5m", "15m", "30m", "60m", "90m", "1d", "5d", "1wk", "1mo", "3mo"
for ticker in tickers:
    print(f"\nFetching {ticker} 1-minute data...")
    data = yf.download(ticker, interval="1m", period="5d", progress=False)
    print("finished")

Fetching AAPL 1-minute data...
finished

Fetching AMZN 1-minute data...
finished

Fetching GOOG 1-minute data...
finished

Fetching INTC 1-minute data...
finished

Fetching MSFT 1-minute data...
finished

In [ ]:
#digital currency

In [6]:
#minutes 
from alpaca.data.historical import CryptoHistoricalDataClient

client = CryptoHistoricalDataClient()

from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime

# Creating request object
request_params = CryptoBarsRequest(
  symbol_or_symbols=["BTC/USD"],
  timeframe=TimeFrame.Minute,
 #timeframe=TimeFrame.Day,
 #timeframe=TimeFrame.Hour,
  start=datetime(2022, 9, 1),
  end=datetime(2022, 9, 7)
)

# Retrieve daily bars for Bitcoin in a DataFrame and printing it
btc_bars = client.get_crypto_bars(request_params)

# Convert to dataframe
btc_bars.df

                                       open      high       low     close  \
symbol  timestamp
BTC/USD 2022-09-01 00:00:00+00:00  20051.81  20055.59  20023.52  20023.52
        2022-09-01 00:01:00+00:00  20023.52  20035.29  20000.00  20035.29
        2022-09-01 00:02:00+00:00  20031.38  20071.79  20020.00  20064.99
        2022-09-01 00:03:00+00:00  20065.36  20107.23  20065.36  20103.30
        2022-09-01 00:04:00+00:00  20107.23  20110.44  20082.00  20110.05
...                                     ...       ...       ...       ...
        2022-09-06 23:56:00+00:00  18811.78  18815.46  18787.35  18799.52
        2022-09-06 23:57:00+00:00  18795.31  18814.56  18788.13  18806.96
        2022-09-06 23:58:00+00:00  18815.12  18815.12  18795.00  18806.34
        2022-09-06 23:59:00+00:00  18805.38  18808.07  18780.12  18790.39
        2022-09-07 00:00:00+00:00  18789.40  18813.55  18762.62  18775.17

                                      volume  trade_count          vwap
symbol  timestamp
BTC/USD 2022-09-01 00:00:00+00:00   6.184083        123.0  20043.889989
        2022-09-01 00:01:00+00:00   7.636889        106.0  20007.383661
        2022-09-01 00:02:00+00:00  17.616520        187.0  20044.975294
        2022-09-01 00:03:00+00:00   7.448067        140.0  20087.130855
        2022-09-01 00:04:00+00:00   6.151111        107.0  20100.040740
...                                      ...          ...           ...
        2022-09-06 23:56:00+00:00  22.110418        131.0  18802.059210
        2022-09-06 23:57:00+00:00  10.996487         73.0  18799.604531
        2022-09-06 23:58:00+00:00   5.755198         78.0  18805.219403
        2022-09-06 23:59:00+00:00  13.904856        120.0  18792.657268
        2022-09-07 00:00:00+00:00  24.437612        210.0  18787.999418

[8630 rows x 7 columns]

In [8]:
#hours
from alpaca.data.historical import CryptoHistoricalDataClient

client = CryptoHistoricalDataClient()

from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime

# Creating request object
request_params = CryptoBarsRequest(
  symbol_or_symbols=["BTC/USD"],
 #timeframe=TimeFrame.Minute,
 #timeframe=TimeFrame.Day,
  timeframe=TimeFrame.Hour,
  start=datetime(2022, 9, 1),
  end=datetime(2022, 9, 7)
)

# Retrieve daily bars for Bitcoin in a DataFrame and printing it
btc_bars = client.get_crypto_bars(request_params)

# Convert to dataframe
btc_bars.df

                                       open      high       low     close  \
symbol  timestamp
BTC/USD 2022-09-01 00:00:00+00:00  20051.81  20139.53  19915.87  20060.81
        2022-09-01 01:00:00+00:00  20061.09  20183.83  20052.47  20123.27
        2022-09-01 02:00:00+00:00  20128.64  20205.83  20070.18  20117.06
        2022-09-01 03:00:00+00:00  20119.07  20179.31  19925.00  20030.01
        2022-09-01 04:00:00+00:00  20026.42  20094.22  19977.91  20056.65
...                                     ...       ...       ...       ...
        2022-09-06 20:00:00+00:00  18825.90  19025.99  18668.90  18987.58
        2022-09-06 21:00:00+00:00  18992.25  19085.38  18927.10  18981.78
        2022-09-06 22:00:00+00:00  18982.18  19007.99  18883.14  18912.40
        2022-09-06 23:00:00+00:00  18905.73  18923.21  18780.12  18790.39
        2022-09-07 00:00:00+00:00  18789.40  18876.63  18655.93  18833.97

                                       volume  trade_count          vwap
symbol  timestamp
BTC/USD 2022-09-01 00:00:00+00:00  427.709965       5354.0  20041.305160
        2022-09-01 01:00:00+00:00  252.154395       3765.0  20116.353524
        2022-09-01 02:00:00+00:00  212.917917       2940.0  20148.623041
        2022-09-01 03:00:00+00:00  342.121451       4461.0  20068.579371
        2022-09-01 04:00:00+00:00  182.830505       3284.0  20040.001919
...                                       ...          ...           ...
        2022-09-06 20:00:00+00:00  895.295245       8523.0  18859.850937
        2022-09-06 21:00:00+00:00  217.384639       2938.0  18995.377815
        2022-09-06 22:00:00+00:00  276.033813       2913.0  18944.703221
        2022-09-06 23:00:00+00:00  315.551183       3664.0  18849.569550
        2022-09-07 00:00:00+00:00  601.409403       5868.0  18778.345033

[145 rows x 7 columns]

In [10]:
#days
from alpaca.data.historical import CryptoHistoricalDataClient

client = CryptoHistoricalDataClient()

from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime

# Creating request object
request_params = CryptoBarsRequest(
  symbol_or_symbols=["BTC/USD"],
 #timeframe=TimeFrame.Minute,
  timeframe=TimeFrame.Day,
 #timeframe=TimeFrame.Hour,
  start=datetime(2022, 9, 1),
  end=datetime(2022, 9, 7)
)

# Retrieve daily bars for Bitcoin in a DataFrame and printing it
btc_bars = client.get_crypto_bars(request_params)

# Convert to dataframe
btc_bars.df

                                       open      high       low     close  \
symbol  timestamp
BTC/USD 2022-09-01 05:00:00+00:00  20055.79  20292.00  19564.86  20156.76
        2022-09-02 05:00:00+00:00  20156.76  20444.00  19757.72  19919.47
        2022-09-03 05:00:00+00:00  19924.83  19968.20  19658.04  19806.11
        2022-09-04 05:00:00+00:00  19805.39  20058.00  19587.86  19888.67
        2022-09-05 05:00:00+00:00  19888.67  20180.50  19635.96  19760.56
        2022-09-06 05:00:00+00:00  19761.39  20026.91  18534.06  18724.59

                                         volume  trade_count          vwap
symbol  timestamp
BTC/USD 2022-09-01 05:00:00+00:00   7141.975485     110122.0  19934.167845
        2022-09-02 05:00:00+00:00   7165.911879      96231.0  20075.200868
        2022-09-03 05:00:00+00:00   2677.652012      51551.0  19800.185480
        2022-09-04 05:00:00+00:00   4325.678790      62082.0  19834.451414
        2022-09-05 05:00:00+00:00   6274.552824      84784.0  19812.095982
        2022-09-06 05:00:00+00:00  11217.789784     128106.0  19266.835520